# -*- makefile-mode -*-
CC=gcc
EMACS=emacs
MASTER = Chapter3
BATCH_EMACS=$(EMACS) --batch -Q -l ~/.emacs.d/my-org-config.el -l ~/.emacs.d/my-org-extras.el $(MASTER).org
REQUIREMENTS=octave gnuplot sh

all: $(MASTER).pdf

$(MASTER).tex: $(MASTER).org
	$(BATCH_EMACS) -f mark-whole-buffer -f org-babel-execute-buffer -f org-export-as-latex

$(MASTER).pdf: $(MASTER).tex
	rm -f $(MASTER).aux 
	if pdflatex $< </dev/null; then \
		true; \
	else \
		stat=$$?; touch $@; exit $$stat; \
	fi
	makeglossaries $(MASTER)	
	bibtex $(MASTER)
	while grep "Rerun to get" $(MASTER).log; do \
		if pdflatex $< </dev/null; then \
			true; \
		else \
			stat=$$?; touch $(MASTER).pdf; exit $$stat; \
		fi; \
	done

$(MASTER).ps: $(MASTER).pdf
	pdf2ps $(MASTER).pdf

cocktail.c: $(MASTER).org
	$(BATCH_EMACS) -f org-$(MASTER)-tangle

cocktail: cocktail.c
	$(CC) -o cocktail cocktail.c

check:
	for req in $(REQUIREMENTS); do \
		which $$req > /dev/null || echo "MISSING DEPENDENCY $$req"; \
	done

clean:
	find . -type f -name "*.out" -o -name "*.dvi" \
		-o -name "*.aux" -o -name "*.log" \
	        -o -name "*.lof" -o -name "*.lot"  \
		-o -name "*.glg" -o -name "*.gls" -o -name "*.glo" \
	        -o -name "*.blg" -o -name "*.bbl" \
	        -o -name "*.toc"  -o -name "*.fls" \
	        -o -name "*.alg" -o -name "*.acr" -o -name "*.acn" \
	        -o -name "*.tdo" -o -name "*.ist" -o -name "*.d" \
	        -o -name "*.make" -o -name "*.cookie" \
		-o -name "_region_.prv*" | grep -v ".hg/" | xargs -tn1 rm -f 

