#+LaTeX_CLASS: beamer
#+MACRO: BEAMERMODE presentation
#+MACRO: BEAMERTHEME default
#+MACRO: BEAMERCOLORTHEME dove
#+MACRO: BEAMERSUBJECT cochlear nucleus, neural modelling, simple optimisation
#+MACRO: BEAMERINSTITUTE The University of Melbourne, Department of Otolaryngology, and the Bionic Ear Institute
#+TITLE: Constructing realistic microcircuits: the Cochlear Nucleus stellate model
#+AUTHOR: Michael A. Eager
#+LaTeX_header: natbib
#+LaTeX_header: tabularx

#+LaTeX:\include{../manuscript/glossary}
* Chapter 3: Simple optimisation of the cochlear nucleus stellate network
** Overview

   1. Introduction
   2. Golgi Model: Fitting simple model to rate level data 
   3. D-stellate Cell Model: GABAergic effects on click recovery
   4. Tuberculoventral Cell Model: Asymmetric wide-band inhibition affects TV response to notch noise
   5. Questions
    
   
** Introduction
#+begin_LaTeX
  \begin{block}{Cochlear Nucleus Stellate Network}
       \makebox[0pt][l]{\only<1>{\includegraphics[width=\columnwidth,keepaspectratio]{gfx/CNcircuit.png}}}%
   %    \makebox[0pt][l]{\only<2>{\includegraphics[width=\columnwidth,keepaspectratio]{gfx/CNcircuit-2.PNG}}}%
   %    \makebox[0pt][l]{\only<3>{\includegraphics[width=\columnwidth,keepaspectratio]{gfx/CNcircuit-3.PNG}}}%
   %    \makebox[0pt][l]{\only<4>{\includegraphics[width=\columnwidth,keepaspectratio]{gfx/CNcircuit-4.PNG}}}%
   %    \makebox[0pt][l]{\only<5>{\includegraphics[width=\columnwidth,keepaspectratio]{gfx/CNcircuit-5.PNG}}}%
   %    \makebox[0pt][l]{\only<6>{\includegraphics[width=\columnwidth,keepaspectratio]{gfx/CNcircuit-6.PNG}}}\\
  \end{block}
#+end_LaTeX
    

** Golgi (GABA) Model 
*** Experimental evidence

- Anatomical \citep{BensonBerglundEtAl:1996}
    - LSR fibers proj to GCD
- Morphological \citep{FerragamoGolding:1998a}
    - small cell (12-15 micron soma), uniform dendrites and axonal
      collaterals 100 micron 
- Intracellular \citep{FerragamoGolding:1998a} (mice, GCD \it{in vitro})
    - type-I~current clamp response
    - delay from shock to AN of 0.7 ms relative to the core VCN units.
- Physiological \citep{GhoshalKim:1997} (marginal shell, 5 units)
    - monotonic response to tones and noise 

** Golgi (GABA) Model 
*** Key factors in designing Golgi model

- Choosing neural model: HH-type or Poisson

- Problem of monotonic excitation at low level
  - added HSR to model to avoid added computation of MSR

- Spread of ANF to GCD more diffuse than core VCN
 - are we spoiling the broth too early? 

** Golgi (GABA) Model 
*** Implementation
 
- Generate  auditory filterbank vectors (\textbf{L} and \textbf{H})
  and golgi alpha function
- Create Golgi vectors from AN vectors
  1. For each channel, create 2 Golgi weighted vector across filterbank:\mu = channel position, \sigma^2 = spatial spread of LSR \to Golgi
  2. Create Golgi vectors by summating ANF inputs weighted by \textbf{w}   
  3. Convolve the golgi vector with the alpha synaptic function 
#+begin_LaTeX
\begin{eqnarray}
 w(i,j) = \frac{1}{\sigma \sqrt{2\pi}} \exp \left\{-\frac{(i-j)^2}{2\sigma^2}\right\}, i,j \in [0,nchannels-1] \\
\mathbf{g}_i = \sum^{i} w_L(i)\mathbf{L}_i + w_H(i)\mathbf{H}_i \\
\mathbf{G}_i = \mathbf{g}_i\quad \ast\quad f_{\alpha} \\
\end{eqnarray}
#+end_LaTeX
- Create spikes from golgi vectors using Jackson's spike generator 

** Golgi (GABA) Model 
*** Optimisation Procedure
- *Parameters*:
 * golgi_spatial_filter_variance_LSR: spatial variance \LSRGLG
 * golgi_syn_filter_scale_factor: alpha function scale factor
 * weight_sum_LSR, weight_sum_HSR: golgi weighted vector sums factor
 * golgi_spon: spontaneous rate of golgi model
- *Fitting Data*: 
 * monotonic rate-level curve, unit S03-07 (CF 21 kHz) Ghoshal and Kim (1997) 
- *Optimisation*: 
 * Measure spike rate of golgi model at several sound levels, calc mean squared error between experimental data and golgi
  model data

** Golgi (GABA) Model 
*** Results

- golgi_spatial_filter_variance_LSR = 2.4837
- golgi_syn_filter_scale_factor = 1.00
- weight_sum_LSR = 0.5166
- weight_sum_HSR = 0.0487
- golgi_spon = 3.7271

** Golgi (GABA) Model 
*** Outcomes

- Good fit of golgi model to Ghoshal and Kim data, using just the tone
rate-level.

** D Stellate Cell Model
*** Experimental evidence
- Morphological 
  * large Multipolar cell
  * electrotonic dendrites stretching 200 microns (one third of VCN), one half DCN, cCN 
  * receive large number of ANF syn to dend and soma
  * receive large number of Gly and GABA syn to soma dend
- Intracellular
  * type I-II current clamp response
  * presence of Ih and small amounts of KLT currents
  * delay from shock to ANFs less than 1 ms 
- Physiological 
  * Onset chopper PSTH, fast narrow FSL 
  * Wide response area (+1 oct and -2 oct)
  * high sync index, Low-pass MTF
  * monotonic response to tones and noise 

** D Stellate Cell Model
*** Key factors in designing D-stellate cell model

- Choosing neural model: type I-II Rothman and Manis model
  * with/without dendrites
  * variable KLT, leak conductance

- Problems
  * ANF spread to DS cells well documented (decision made to
    fix params due to large computational task of calc response area) 
  * short delay recovery responses (2,3,4 ms) were not successful upon
    first model, included DS leak and KLT conductances to allow cell
    behaviour to be fit

** D Stellate Cell Model
*** Implementation
 
- Generate AN vectors in auditory filterbank
- Create Golgi filterbank
- Pass AN and Golgi spikes onto single DS cell model in NEURON


** D Stellate Cell Model
*** Optimisation Procedure
- *Parameters*
# #+CAPTION: DS model parameters requiring optimisation
# #+LABEL: tbl:DSparams
#+begin_LaTeX
\begin{tabularx}{\linewidth}{lXX} 
\textbf{Parameters}   & \textbf{Range} & \\ \hline
 \wHSRDS     & [0.00001,0.05] $\mu$ S    & Weight of HSR syn on DS                                                                                                                                                         \\
 \wLSRDS            & [0.00001,0.05] $\mu$ S    & Weight of LSR syn on DS                                                                                                                                                         \\
 $\tau_{GABA2}$       & [0.1,50.0] ms           & \GABAa synapse decay constant                                                                                                                                                   \\
 $\bar{g}_{leak}$     & [0.00001,0.05] Scm$^{-2}$ & DS cell leak conductance                                                                                                                                                        \\
                    &                         &                                                                                                                                                                                 \\
 \textbf{Fixed Parameters} & \textbf{Value}                 &                                                                                                                                                                                 \\ \hline
 \nGLGDS            & 25                      & Number of GABA syn on DS cells                                                                                                                                                  \\
 \dGLGDS            & 0.5 ms                  & Combination of conductance and synaptic delay. The effect of Golgi cells on DS is delayed by the extra 0.7~ms delay from ANF to Golgi, plus the slow peak of \GABAa inhibition. \\
\end{tabularx}
#+end_LaTeX
- *Fitting Data*: Click recovery data from \citep{BackoffPalombiEtAl:1997} 
- *Optimisation*: Pass 5 double clicks with recovery periods
  (2,3,4,8,16 ms) through model.  Measure DS response for 2ms.  Calc
  mean squared error between ratio of recovery response (Weighting required)

** D Stellate Cell Model
*** Results

#+LaTeX:\includegraphics[keepaspectratio=true,angle=-90,width=0.9\textwidth]{./gfx/DS_ClickRecovery_result}

** D Stellate Cell Model
*** Outcomes

- DS cell model and synaptic inputs are fitted to a reasonable degree

- Weighting procedure was needed to emphasise curvature of recovery at narrow click separation


** Tuberculoventral Cell Model
*** Experimental evidence
Morphological 
    1. vertical/multipolar cell in deep layer of DCN \citep{Rhode:1999}
    2. receive small  number of ANF syn to dend 
    4. receive large number of Gly and GABA syn to soma dend
Intracellular \citep{OertelWickesberg:1993}
    1. type I current clamp response
    2. presence of glycine
    3. 
Physiological \citep{Rhode:1999,SpirouDavisEtAl:1999}
    1. type II, wide chopper PSTH 
    2. Narrow response area, non-monotonic RL
    3. poor response to noise and clicks
    4. asymmetric response to notch noise \citep{ReissYoung:2005}

** Tuberculoventral Cell Model
*** Key factors in designing Golgi model

- Choosing neural model: type I-classic Rothman and Manis model
 - without dendrites

- Problems
  - larger network of CN model

** Tuberculoventral Cell Model
*** Implementation
 
- Generate AN vectors in auditory filterbank
- Create Golgi vectors from AN vectors
- Generate  AN and Golgi spikes 
- TV and DS cell models

** Tuberculoventral Cell Model
*** Optimisation Procedure

Syn.~weight \DSTV & $\wDSTV \quad\to\quad [0.00001,0.05]\quad\mu{\rm S}$ \\\hline
Syn.~weight ANF to DS       & $\wANFTV \quad\to\quad [0.00001,0.05] \quad \mu{\rm S}$\\\hline
No.~LSR to TV       & $\nLSRTV \quad\to\quad [0.00001,0.05] \quad \mu{\rm S}$\\\hline
No.~HSR to TV       & $\nHSRTV \quad\to\quad [0.00001,0.05] \quad \mu{\rm S}$\\\hline
Spread of \DSTV       & $\sDSTV \quad\to\quad [0,5] \quad {\rm Channels}$\\\hline
Offset \DSTV       & $\oDSTV \quad\to\quad [0,5] \quad {\rm Channels}$\\\hline


- *Parameters*
# #+CAPTION: TV model parameters requiring optimisation
# #+LABEL: tbl:TVparams
# #+ATTR_LaTeX: tabularx align=lXX width=\linewidth
#+begin_LaTeX
\begin{tabularx}{\linewidth}{lXX}
 \textbf{Parameters} | \textbf{Range} \\ \hline
 \wDSTV              & [0.00001,0.05] \mu S     & Weight of DS syn on TV                           \\
 \wANFTV             & [0.00001,0.05] \mu S     & Weight of ANF syn on TV                          \\
 \nLSRTV             & [0,64]                   & No.~LSR to TV                                    \\
 \nHSRTV             & [0,64]                   & No.~HSR to TV                                    \\
 \sDSTV              & [1,10]                   & Spread of DS connections onto TV                 \\
 \oDSTV              & [0,10]                   & Offset of center point of DS connections onto TV \\
#+end_LaTeX
- *Fitting Data*: Notch noise data from \citep{ReissYoung:2005} 
- *Optimisation*: Measure DS and TV response across network.  Calc
  mean squared error between Reiss data and TV mean rate response (Weighting required)

** Tuberculoventral Cell Model
*** Results

#+LaTeX:\includegraphics[keepaspectratio=true,angle=-90,width=0.9\textwidth]{./gfx/CN_rateplace_10_0.5}
 
** Tuberculoventral Cell Model
*** Results
#+begin_LaTeX
\begin{tabularx}{lXX}
\wDSTV & 0.0029 $\mu$S\\
\wANFTV & 0.00017 $\mu$S \\
\nHSRTV & 8 $\mu$S \\
\nLSRTV &14 $\mu$S \\
\sDSTV & 2.1 \\
\oDSTV & 0.24 \\
\end{tabularx}
#+end_LaTeX

- *Error*  0.0167  (MSE Normalised rate between 5-40kHz channels)
 * only one run before ANS, needs verification 

#+BIBLIOGRAPHY: ../manuscript/bib/MyBib plainnat option:-d


   
   
   


   

# \ref{fig:SED-HR4049}

#      #+CAPTION: A long table
#      #+LABEL: tbl:long
#      #+ATTR_LaTeX: longtable align=l|lp{3cm}r|l
#      | ..... | ..... |
#      | ..... | ..... |
#      #+CAPTION:    The black-body emission of the disk around HR 4049
#      #+LABEL:      fig:SED-HR4049
#      #+ATTR_LaTeX: width=5cm,angle=90
#      [[./im g/sed-hr4049.pdf]]

# http://orgmode.org/worg/org-tutorials/org-beamer/tutorial.php

** A more complex slide
This slide illustrates the use of Beamer blocks.  The following text,
with its own headline, is displayed in a block:
*** Org mode increases productivity                               :B_theorem:
    :PROPERTIES:
    :BEAMER_env: theorem
    :END:
    - org mode means not having to remember LaTeX commands.
    - it is based on ascii text which is inherently portable.
    - Emacs!

    \hfill \(\qed\)

** Two columns

*** A block                                           :B_ignoreheading:BMCOL:
    :PROPERTIES:
    :BEAMER_env: ignoreheading
    :BEAMER_col: 0.4
    :END:
    - this slide consists of two columns
    - the first (left) column has no heading and consists of text
    - the second (right) column has an image and is enclosed in an
      @example@ block

*** A screenshot                                            :BMCOL:B_example:
    :PROPERTIES:
    :BEAMER_col: 0.6
    :BEAMER_env: example
    :END:
#+ATTR_LATEX: width=\textwidth
    file://../gfx/CNcircuit.png


** Org-babel latex figure
#+begin_src latex :file fsa.pdf :packages '(("" "tikz")) :pdfwidth 3in :pdfheight 3in
  % Define block styles
  \usetikzlibrary{shapes,arrows}
  \tikzstyle{astate} = [circle, draw, text centered, font=\footnotesize, fill=blue!25]
  \tikzstyle{rstate} = [circle, draw, text centered, font=\footnotesize, fill=red!25]

  \begin{tikzpicture}[->,>=stealth', shorten >=1pt, auto, node distance=2.8cm, semithick]
    \node [astate] (1) at (0,0) {1};
    \node [astate] (2) at (1,0) {2};
    \node [rstate] (3) at (2,0) {3};
    \path (1) edge [bend left] node {b} (2)
          (2) edge node {b} (3)
          (2) edge [bend left] node {a} (1)
          (3) edge [loop above] node {(a, b)} (3);
  \end{tikzpicture}
#+end_src


#+begin_LaTeX
\begin{eqnarray}
\end{eqnarray}
#+end_LaTeX

#+begin_LaTeX
\begin{lstlisting}[language=c]
\end{lstlisting}
#+end_LaTeX
